# Generated by Django 4.2.3 on 2023-07-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('mode', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('IN_PROCESS', 'In Process'), ('COMPLETE', 'Complete'), ('DELIVERED', 'Delivered')], default='NONE', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_vendor_transaction', to='user.user')),
            ],
        ),
    ]
