# Generated by Django 4.2.3 on 2023-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=32)),
                ('confirmPassword', models.CharField(max_length=32)),
                ('admin', models.BooleanField(default=False)),
                ('vendor', models.BooleanField(default=False)),
                ('chef', models.BooleanField(default=False)),
                ('agent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registeredAt', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now_add=True)),
                ('intro', models.IntegerField(blank=True, default=0, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
