# Generated by Django 4.2.3 on 2023-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_confirmpassword_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='agent',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='chef',
            new_name='is_chef',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vendor',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
