# Generated by Django 4.2.2 on 2023-07-08 05:50

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_middlename_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default='1234567890', validators=[user.models.validate_digit_length]),
        ),
    ]
