# Generated by Django 4.2.3 on 2023-07-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('IN_PROCESS', 'In Process'), ('COMPLETE', 'Complete'), ('DELIVERED', 'Delivered')], default='NONE', max_length=10)),
                ('subTotal', models.FloatField(blank=True, default=0, null=True)),
                ('itemDiscount', models.IntegerField(blank=True, default=0, null=True)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('shipping', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('promo', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('grandTotal', models.FloatField(blank=True, default=0, null=True)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_vendor_order', to='user.user')),
            ],
        ),
    ]
